"""initial_schema

Revision ID: 300c1a2a7c7f
Revises: 
Create Date: 2025-08-08 16:36:34.131103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = '300c1a2a7c7f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # pgvector 확장 생성
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_chat_feedback',
    sa.Column('feedback_id', sa.Integer(), autoincrement=True, nullable=False, comment='피드백 ID'),
    sa.Column('chat_id', sa.Integer(), nullable=False, comment='채팅 ID'),
    sa.Column('user_emp_no', sa.String(length=20), nullable=False, comment='사용자 사번'),
    sa.Column('feedback_type', sa.String(length=20), nullable=False, comment='피드백 유형 (rating/thumbs/comment)'),
    sa.Column('rating_score', sa.Integer(), nullable=True, comment='평점 (1-5)'),
    sa.Column('is_helpful', sa.Boolean(), nullable=True, comment='도움이 되었는지 여부'),
    sa.Column('feedback_comment', sa.Text(), nullable=True, comment='피드백 코멘트'),
    sa.Column('improvement_suggestion', sa.Text(), nullable=True, comment='개선 제안'),
    sa.Column('feedback_category', sa.String(length=50), nullable=True, comment='피드백 카테고리'),
    sa.Column('issue_type', sa.String(length=50), nullable=True, comment='이슈 유형'),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='생성일'),
    sa.PrimaryKeyConstraint('feedback_id')
    )
    op.create_table('tb_chat_history',
    sa.Column('chat_id', sa.Integer(), autoincrement=True, nullable=False, comment='채팅 ID'),
    sa.Column('session_id', sa.String(length=100), nullable=False, comment='세션 ID'),
    sa.Column('user_emp_no', sa.String(length=20), nullable=False, comment='사용자 사번'),
    sa.Column('knowledge_container_id', sa.String(length=50), nullable=True, comment='대화 컨텍스트 컨테이너'),
    sa.Column('user_permission_level', sa.String(length=20), nullable=True, comment='사용자 권한 레벨'),
    sa.Column('accessible_containers', sa.ARRAY(sa.String(length=50)), nullable=True, comment='접근 가능한 컨테이너 목록'),
    sa.Column('user_message', sa.Text(), nullable=False, comment='사용자 질문'),
    sa.Column('assistant_response', sa.Text(), nullable=False, comment='AI 응답'),
    sa.Column('search_query', sa.Text(), nullable=True, comment='검색 쿼리'),
    sa.Column('search_results', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='검색 결과 (JSON)'),
    sa.Column('referenced_documents', sa.ARRAY(sa.Integer()), nullable=True, comment='참조된 문서 ID 목록'),
    sa.Column('search_score', sa.String(length=10), nullable=True, comment='검색 점수'),
    sa.Column('model_used', sa.String(length=50), nullable=True, comment='사용된 AI 모델'),
    sa.Column('model_parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='모델 파라미터 (JSON)'),
    sa.Column('response_time_ms', sa.Integer(), nullable=True, comment='응답 시간 (밀리초)'),
    sa.Column('conversation_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='대화 컨텍스트 (JSON)'),
    sa.Column('feedback_score', sa.Integer(), nullable=True, comment='사용자 피드백 점수 (1-5)'),
    sa.Column('feedback_comment', sa.Text(), nullable=True, comment='사용자 피드백 코멘트'),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='생성일'),
    sa.PrimaryKeyConstraint('chat_id')
    )
    op.create_table('tb_chat_sessions',
    sa.Column('session_id', sa.String(length=100), nullable=False, comment='세션 ID'),
    sa.Column('user_emp_no', sa.String(length=20), nullable=False, comment='사용자 사번'),
    sa.Column('session_name', sa.String(length=200), nullable=True, comment='세션명'),
    sa.Column('session_description', sa.Text(), nullable=True, comment='세션 설명'),
    sa.Column('default_container_id', sa.String(length=50), nullable=True, comment='기본 컨테이너 ID'),
    sa.Column('allowed_containers', sa.ARRAY(sa.String(length=50)), nullable=True, comment='허용된 컨테이너 목록'),
    sa.Column('max_messages', sa.Integer(), nullable=False, comment='최대 메시지 수'),
    sa.Column('session_timeout_minutes', sa.Integer(), nullable=False, comment='세션 타임아웃 (분)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='활성화 여부'),
    sa.Column('last_activity', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='마지막 활동 시간'),
    sa.Column('message_count', sa.Integer(), nullable=False, comment='메시지 수'),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='생성일'),
    sa.Column('last_modified_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='최종 수정일'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('tb_cmns_cd_grp_item',
    sa.Column('grp_cd', sa.String(length=20), nullable=False, comment='그룹 코드'),
    sa.Column('item_cd', sa.String(length=20), nullable=False, comment='아이템 코드'),
    sa.Column('item_nm', sa.String(length=100), nullable=False, comment='아이템명'),
    sa.Column('item_desc', sa.String(length=500), nullable=True, comment='아이템 설명'),
    sa.Column('sort_ord', sa.Integer(), nullable=True, comment='정렬 순서'),
    sa.Column('use_yn', sa.String(length=1), nullable=False, comment='사용 여부'),
    sa.Column('created_by', sa.String(length=50), nullable=True, comment='생성자'),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='생성일'),
    sa.Column('updated_by', sa.String(length=50), nullable=True, comment='수정자'),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='수정일'),
    sa.PrimaryKeyConstraint('grp_cd', 'item_cd')
    )
    op.create_table('tb_container_categories',
    sa.Column('container_category_id', sa.Integer(), autoincrement=True, nullable=False, comment='컨테이너 카테고리 ID'),
    sa.Column('container_id', sa.String(length=50), nullable=False, comment='컨테이너 ID'),
    sa.Column('category_id', sa.String(length=20), nullable=False, comment='카테고리 ID'),
    sa.Column('is_primary', sa.Boolean(), nullable=False, comment='주 카테고리 여부'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='활성화 여부'),
    sa.Column('created_by', sa.String(length=20), nullable=True, comment='생성자'),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='생성일'),
    sa.PrimaryKeyConstraint('container_category_id')
    )
    op.create_table('tb_file_bss_info',
    sa.Column('file_bss_info_sno', sa.Integer(), autoincrement=True, nullable=False, comment='파일 기본 정보 일련번호'),
    sa.Column('drcy_sno', sa.Integer(), nullable=False, comment='디렉토리 일련번호'),
    sa.Column('file_dtl_info_sno', sa.Integer(), nullable=True, comment='파일 상세 정보 일련번호'),
    sa.Column('file_lgc_nm', sa.String(length=255), nullable=False, comment='파일 논리명'),
    sa.Column('file_psl_nm', sa.String(length=255), nullable=False, comment='파일 물리명'),
    sa.Column('file_extsn', sa.String(length=10), nullable=False, comment='파일 확장자'),
    sa.Column('path', sa.String(length=500), nullable=False, comment='파일 저장 경로'),
    sa.Column('del_yn', sa.CHAR(length=1), nullable=False, comment='삭제 여부 (Y/N)'),
    sa.Column('created_by', sa.String(length=50), nullable=True, comment='생성자 ID'),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='생성일시'),
    sa.Column('last_modified_by', sa.String(length=50), nullable=True, comment='최종 수정자 ID'),
    sa.Column('last_modified_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='최종 수정일시'),
    sa.Column('korean_metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='한국어 메타데이터'),
    sa.Column('chunk_count', sa.Integer(), nullable=True, comment='청크 개수'),
    sa.Column('knowledge_container_id', sa.String(length=50), nullable=True, comment='지식 컨테이너 ID'),
    sa.Column('permission_level', sa.String(length=20), nullable=False, comment='권한 레벨'),
    sa.Column('access_restrictions', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='접근 제한'),
    sa.Column('owner_emp_no', sa.String(length=20), nullable=True, comment='소유자 사번'),
    sa.Column('last_accessed_date', sa.DateTime(timezone=True), nullable=True, comment='마지막 접근일'),
    sa.Column('access_count', sa.Integer(), nullable=False, comment='접근 횟수'),
    sa.PrimaryKeyConstraint('file_bss_info_sno')
    )
    op.create_index('idx_file_bss_info_accessed', 'tb_file_bss_info', ['last_accessed_date'], unique=False)
    op.create_index('idx_file_bss_info_container', 'tb_file_bss_info', ['knowledge_container_id'], unique=False)
    op.create_index('idx_file_bss_info_owner', 'tb_file_bss_info', ['owner_emp_no'], unique=False)
    op.create_index('idx_file_bss_info_permission', 'tb_file_bss_info', ['permission_level'], unique=False)
    op.create_index('idx_tb_file_bss_info_del_yn', 'tb_file_bss_info', ['del_yn'], unique=False)
    op.create_table('tb_file_dtl_info',
    sa.Column('file_dtl_info_sno', sa.Integer(), autoincrement=True, nullable=False, comment='파일 상세 정보 일련번호'),
    sa.Column('sj', sa.String(length=500), nullable=True, comment='파일 제목'),
    sa.Column('cn', sa.Text(), nullable=True, comment='파일 내용 요약'),
    sa.Column('kwrd', sa.String(length=1000), nullable=True, comment='키워드 (콤마 구분)'),
    sa.Column('authr', sa.String(length=100), nullable=True, comment='작성자'),
    sa.Column('wrt_de', sa.String(length=8), nullable=True, comment='작성일 (YYYYMMDD)'),
    sa.Column('updt_de', sa.String(length=8), nullable=True, comment='수정일 (YYYYMMDD)'),
    sa.Column('ctgry_cd', sa.String(length=20), nullable=True, comment='카테고리 코드'),
    sa.Column('ctgry_nm', sa.String(length=100), nullable=True, comment='카테고리명'),
    sa.Column('file_sz', sa.Integer(), nullable=True, comment='파일 크기 (bytes)'),
    sa.Column('page_co', sa.Integer(), nullable=True, comment='페이지 수'),
    sa.Column('lang_cd', sa.String(length=10), nullable=True, comment='언어 코드'),
    sa.Column('secrty_lvl', sa.String(length=10), nullable=True, comment='보안 등급'),
    sa.Column('vrsn', sa.String(length=20), nullable=True, comment='버전'),
    sa.Column('tag', sa.String(length=500), nullable=True, comment='태그 (콤마 구분)'),
    sa.Column('sumry', sa.Text(), nullable=True, comment='요약'),
    sa.Column('del_yn', sa.CHAR(length=1), nullable=False, comment='삭제 여부 (Y/N)'),
    sa.Column('created_by', sa.String(length=50), nullable=True, comment='생성자 ID'),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='생성일시'),
    sa.Column('last_modified_by', sa.String(length=50), nullable=True, comment='최종 수정자 ID'),
    sa.Column('last_modified_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='최종 수정일시'),
    sa.PrimaryKeyConstraint('file_dtl_info_sno')
    )
    op.create_index('idx_tb_file_dtl_info_authr', 'tb_file_dtl_info', ['authr'], unique=False)
    op.create_index('idx_tb_file_dtl_info_ctgry_cd', 'tb_file_dtl_info', ['ctgry_cd'], unique=False)
    op.create_index('idx_tb_file_dtl_info_del_yn', 'tb_file_dtl_info', ['del_yn'], unique=False)
    op.create_index('idx_tb_file_dtl_info_sj', 'tb_file_dtl_info', ['sj'], unique=False)
    op.create_table('tb_knowledge_access_log',
    sa.Column('access_log_id', sa.Integer(), autoincrement=True, nullable=False, comment='접근 로그 ID'),
    sa.Column('user_emp_no', sa.String(length=20), nullable=False, comment='사용자 사번'),
    sa.Column('file_bss_info_sno', sa.Integer(), nullable=True, comment='파일 기본 정보 일련번호'),
    sa.Column('knowledge_container_id', sa.String(length=50), nullable=True, comment='지식 컨테이너 ID'),
    sa.Column('access_type', sa.String(length=20), nullable=False, comment='접근 유형 (view/download/search/chat)'),
    sa.Column('access_method', sa.String(length=20), nullable=True, comment='접근 방법 (web/api/mobile)'),
    sa.Column('search_query', sa.Text(), nullable=True, comment='검색 쿼리'),
    sa.Column('search_results_count', sa.Integer(), nullable=True, comment='검색 결과 수'),
    sa.Column('search_method', sa.String(length=20), nullable=True, comment='검색 방법 (semantic/keyword/hybrid)'),
    sa.Column('session_id', sa.String(length=100), nullable=True, comment='세션 ID'),
    sa.Column('ip_address', sa.String(length=50), nullable=True, comment='IP 주소'),
    sa.Column('user_agent', sa.Text(), nullable=True, comment='사용자 에이전트'),
    sa.Column('response_time_ms', sa.Integer(), nullable=True, comment='응답 시간 (밀리초)'),
    sa.Column('is_successful', sa.Boolean(), nullable=False, comment='성공 여부'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='오류 메시지'),
    sa.Column('access_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='접근 일시'),
    sa.PrimaryKeyConstraint('access_log_id')
    )
    op.create_table('tb_knowledge_categories',
    sa.Column('category_id', sa.String(length=20), nullable=False, comment='카테고리 ID'),
    sa.Column('category_name', sa.String(length=100), nullable=False, comment='카테고리명'),
    sa.Column('category_description', sa.Text(), nullable=True, comment='카테고리 설명'),
    sa.Column('parent_category_id', sa.String(length=20), nullable=True, comment='상위 카테고리 ID'),
    sa.Column('category_level', sa.Integer(), nullable=False, comment='카테고리 레벨'),
    sa.Column('category_path', sa.String(length=500), nullable=True, comment='카테고리 경로'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='정렬 순서'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='활성화 여부'),
    sa.Column('document_count', sa.Integer(), nullable=False, comment='문서 수'),
    sa.Column('created_by', sa.String(length=20), nullable=True, comment='생성자'),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='생성일'),
    sa.Column('last_modified_by', sa.String(length=20), nullable=True, comment='최종 수정자'),
    sa.Column('last_modified_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='최종 수정일'),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_table('tb_knowledge_sharing_log',
    sa.Column('sharing_log_id', sa.Integer(), autoincrement=True, nullable=False, comment='공유 로그 ID'),
    sa.Column('sharer_emp_no', sa.String(length=20), nullable=False, comment='공유자 사번'),
    sa.Column('file_bss_info_sno', sa.Integer(), nullable=False, comment='파일 기본 정보 일련번호'),
    sa.Column('knowledge_container_id', sa.String(length=50), nullable=True, comment='지식 컨테이너 ID'),
    sa.Column('sharing_type', sa.String(length=20), nullable=False, comment='공유 유형 (link/download/email)'),
    sa.Column('shared_with', sa.ARRAY(sa.String(length=20)), nullable=True, comment='공유 대상자 목록'),
    sa.Column('sharing_scope', sa.String(length=20), nullable=False, comment='공유 범위 (internal/external/public)'),
    sa.Column('access_permission', sa.String(length=20), nullable=False, comment='접근 권한'),
    sa.Column('expires_date', sa.DateTime(timezone=True), nullable=True, comment='만료일'),
    sa.Column('sharing_note', sa.Text(), nullable=True, comment='공유 메모'),
    sa.Column('sharing_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='공유 일시'),
    sa.PrimaryKeyConstraint('sharing_log_id')
    )
    op.create_table('tb_sap_hr_info',
    sa.Column('emp_no', sa.String(length=20), nullable=False, comment='사번'),
    sa.Column('emp_nm', sa.String(length=100), nullable=False, comment='직원명'),
    sa.Column('dept_cd', sa.String(length=20), nullable=True, comment='부서 코드'),
    sa.Column('dept_nm', sa.String(length=100), nullable=True, comment='부서명'),
    sa.Column('postn_cd', sa.String(length=20), nullable=True, comment='직급 코드'),
    sa.Column('postn_nm', sa.String(length=100), nullable=True, comment='직급명'),
    sa.Column('email', sa.String(length=200), nullable=True, comment='이메일'),
    sa.Column('telno', sa.String(length=20), nullable=True, comment='전화번호'),
    sa.Column('mbtlno', sa.String(length=20), nullable=True, comment='휴대폰번호'),
    sa.Column('entrps_de', sa.String(length=8), nullable=True, comment='입사일 (YYYYMMDD)'),
    sa.Column('rsgntn_de', sa.String(length=8), nullable=True, comment='퇴사일 (YYYYMMDD)'),
    sa.Column('emp_stats_cd', sa.String(length=10), nullable=True, comment='재직 상태'),
    sa.Column('del_yn', sa.String(length=1), nullable=False, comment='삭제 여부'),
    sa.Column('created_by', sa.String(length=50), nullable=True, comment='생성자'),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=True, comment='생성일'),
    sa.Column('last_modified_by', sa.String(length=50), nullable=True, comment='최종 수정자'),
    sa.Column('last_modified_date', sa.DateTime(timezone=True), nullable=True, comment='최종 수정일'),
    sa.PrimaryKeyConstraint('emp_no')
    )
    op.create_index('idx_tb_sap_hr_info_del_yn', 'tb_sap_hr_info', ['del_yn'], unique=False)
    op.create_index('idx_tb_sap_hr_info_dept_cd', 'tb_sap_hr_info', ['dept_cd'], unique=False)
    op.create_index('idx_tb_sap_hr_info_email', 'tb_sap_hr_info', ['email'], unique=False)
    op.create_index('idx_tb_sap_hr_info_emp_stats_cd', 'tb_sap_hr_info', ['emp_stats_cd'], unique=False)
    op.create_table('tb_search_analytics',
    sa.Column('analytics_id', sa.Integer(), autoincrement=True, nullable=False, comment='분석 ID'),
    sa.Column('analytics_date', sa.String(length=8), nullable=False, comment='분석 일자 (YYYYMMDD)'),
    sa.Column('analytics_type', sa.String(length=20), nullable=False, comment='분석 유형 (daily/weekly/monthly)'),
    sa.Column('total_searches', sa.Integer(), nullable=False, comment='총 검색 수'),
    sa.Column('unique_users', sa.Integer(), nullable=False, comment='고유 사용자 수'),
    sa.Column('avg_response_time', sa.Float(), nullable=True, comment='평균 응답 시간'),
    sa.Column('success_rate', sa.Float(), nullable=True, comment='성공률'),
    sa.Column('top_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='인기 검색어 (JSON)'),
    sa.Column('top_documents', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='인기 문서 (JSON)'),
    sa.Column('top_containers', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='인기 컨테이너 (JSON)'),
    sa.Column('user_patterns', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='사용자 패턴 분석 (JSON)'),
    sa.Column('time_patterns', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='시간대별 패턴 (JSON)'),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='생성일'),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='마지막 업데이트'),
    sa.PrimaryKeyConstraint('analytics_id')
    )
    op.create_table('tb_system_settings',
    sa.Column('setting_id', sa.Integer(), autoincrement=True, nullable=False, comment='설정 ID'),
    sa.Column('setting_key', sa.String(length=100), nullable=False, comment='설정 키'),
    sa.Column('setting_value', sa.Text(), nullable=True, comment='설정 값'),
    sa.Column('setting_type', sa.String(length=20), nullable=False, comment='설정 타입 (string/int/boolean/json)'),
    sa.Column('setting_category', sa.String(length=50), nullable=True, comment='설정 카테고리'),
    sa.Column('setting_description', sa.Text(), nullable=True, comment='설정 설명'),
    sa.Column('is_encrypted', sa.Boolean(), nullable=False, comment='암호화 여부'),
    sa.Column('is_system', sa.Boolean(), nullable=False, comment='시스템 설정 여부'),
    sa.Column('created_by', sa.String(length=20), nullable=True, comment='생성자'),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='생성일'),
    sa.Column('last_modified_by', sa.String(length=20), nullable=True, comment='최종 수정자'),
    sa.Column('last_modified_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='최종 수정일'),
    sa.PrimaryKeyConstraint('setting_id'),
    sa.UniqueConstraint('setting_key')
    )
    op.create_table('tb_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('emp_no', sa.String(length=20), nullable=False, comment='사번'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='사용자명'),
    sa.Column('email', sa.String(length=200), nullable=False, comment='이메일'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='해시된 비밀번호'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='활성화 여부'),
    sa.Column('is_admin', sa.Boolean(), nullable=False, comment='관리자 여부'),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True, comment='마지막 로그인 날짜'),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False, comment='로그인 실패 횟수'),
    sa.Column('account_locked_until', sa.DateTime(timezone=True), nullable=True, comment='계정 잠금 해제 시간'),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=False, comment='생성일'),
    sa.Column('last_modified_date', sa.DateTime(timezone=True), nullable=False, comment='최종 수정일'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('emp_no')
    )
    op.create_index('idx_tb_user_email', 'tb_user', ['email'], unique=False)
    op.create_index('idx_tb_user_emp_no', 'tb_user', ['emp_no'], unique=False)
    op.create_index('idx_tb_user_is_active', 'tb_user', ['is_active'], unique=False)
    op.create_table('vs_chat_history_index',
    sa.Column('index_id', sa.Integer(), autoincrement=True, nullable=False, comment='인덱스 ID'),
    sa.Column('chat_id', sa.Integer(), nullable=False, comment='채팅 ID'),
    sa.Column('message_vector', Vector(dim=1024), nullable=False, comment='메시지 벡터 (1024차원)'),
    sa.Column('response_vector', Vector(dim=1024), nullable=True, comment='응답 벡터 (1024차원)'),
    sa.Column('conversation_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='대화 메타데이터 (JSON)'),
    sa.Column('knowledge_container_id', sa.String(length=50), nullable=True, comment='지식 컨테이너 ID'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='활성화 여부'),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='생성일'),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='마지막 업데이트'),
    sa.PrimaryKeyConstraint('index_id')
    )
    op.create_table('vs_doc_contents_chunks',
    sa.Column('chunk_sno', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_bss_info_sno', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('chunk_size', sa.Integer(), nullable=False),
    sa.Column('chunk_embedding', Vector(dim=1024), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('section_title', sa.String(length=200), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True, comment='추출된 키워드 (콤마 구분)'),
    sa.Column('named_entities', sa.Text(), nullable=True, comment='고유명사 (콤마 구분)'),
    sa.Column('knowledge_container_id', sa.String(length=50), nullable=True, comment='지식 컨테이너 ID'),
    sa.Column('metadata_json', sa.Text(), nullable=True, comment='메타데이터 JSON'),
    sa.Column('del_yn', sa.String(length=1), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_modified_by', sa.String(length=50), nullable=True),
    sa.Column('last_modified_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('chunk_sno')
    )
    op.create_index('idx_vs_doc_chunks_container_id', 'vs_doc_contents_chunks', ['knowledge_container_id'], unique=False)
    op.create_index('idx_vs_doc_chunks_del_yn', 'vs_doc_contents_chunks', ['del_yn'], unique=False)
    op.create_index('idx_vs_doc_chunks_embedding', 'vs_doc_contents_chunks', ['chunk_embedding'], unique=False, postgresql_using='ivfflat')
    op.create_index('idx_vs_doc_chunks_file_sno', 'vs_doc_contents_chunks', ['file_bss_info_sno'], unique=False)
    op.create_index('idx_vs_doc_chunks_page_number', 'vs_doc_contents_chunks', ['page_number'], unique=False)
    op.create_index(op.f('ix_vs_doc_contents_chunks_file_bss_info_sno'), 'vs_doc_contents_chunks', ['file_bss_info_sno'], unique=False)
    op.create_table('vs_doc_contents_index',
    sa.Column('id', sa.String(), nullable=False, comment='문서 ID'),
    sa.Column('file_bss_info_sno', sa.Integer(), nullable=False, comment='파일 기본 정보 일련번호'),
    sa.Column('chunk_text', sa.Text(), nullable=False, comment='문서 내용 (기존 chunk_text)'),
    sa.Column('embedding', Vector(dim=1024), nullable=True, comment='임베딩 벡터 (기존 유지)'),
    sa.Column('chunk_index', sa.Integer(), nullable=True, comment='청크 인덱스'),
    sa.Column('chunk_size', sa.Integer(), nullable=True, comment='청크 크기'),
    sa.Column('metadata_json', sa.Text(), nullable=True, comment='메타데이터 JSON'),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='생성일'),
    sa.Column('knowledge_container_id', sa.String(length=50), nullable=True, comment='지식 컨테이너 ID'),
    sa.Column('document_title', sa.String(length=500), nullable=True, comment='문서 제목'),
    sa.Column('keywords', sa.Text(), nullable=True, comment='추출된 키워드 (JSON 배열)'),
    sa.Column('proper_nouns', sa.Text(), nullable=True, comment='고유명사 (JSON 배열)'),
    sa.Column('document_type', sa.String(length=50), nullable=True, comment='문서 유형 (PDF, DOCX, etc)'),
    sa.Column('content_length', sa.Integer(), nullable=True, comment='전체 내용 길이'),
    sa.Column('content_summary', sa.Text(), nullable=True, comment='내용 요약'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='활성화 여부'),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='마지막 업데이트'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_vs_doc_contents_active', 'vs_doc_contents_index', ['is_active'], unique=False)
    op.create_index('idx_vs_doc_contents_container', 'vs_doc_contents_index', ['knowledge_container_id'], unique=False)
    op.create_index('idx_vs_doc_contents_embedding', 'vs_doc_contents_index', ['embedding'], unique=False, postgresql_using='ivfflat')
    op.create_index('idx_vs_doc_contents_file_sno', 'vs_doc_contents_index', ['file_bss_info_sno'], unique=False)
    op.create_index('idx_vs_doc_contents_type', 'vs_doc_contents_index', ['document_type'], unique=False)
    op.create_table('tb_knowledge_containers',
    sa.Column('container_id', sa.String(length=50), nullable=False, comment='컨테이너 ID'),
    sa.Column('container_name', sa.String(length=200), nullable=False, comment='컨테이너 명'),
    sa.Column('parent_container_id', sa.String(length=50), nullable=True, comment='상위 컨테이너 ID'),
    sa.Column('container_type', sa.String(length=20), nullable=False, comment='컨테이너 유형 (company/division/department/team)'),
    sa.Column('sap_org_code', sa.String(length=20), nullable=True, comment='SAP 조직 코드'),
    sa.Column('sap_cost_center', sa.String(length=20), nullable=True, comment='SAP 코스트 센터'),
    sa.Column('org_level', sa.Integer(), nullable=False, comment='조직 레벨 (1=ROOT, 2=DIVISION, 3=DEPARTMENT, 4=TEAM)'),
    sa.Column('org_path', sa.Text(), nullable=True, comment='조직 경로 (/ROOT/DIVISION/DEPARTMENT/TEAM)'),
    sa.Column('description', sa.Text(), nullable=True, comment='컨테이너 설명'),
    sa.Column('knowledge_category', sa.String(length=50), nullable=True, comment='주요 지식 분야'),
    sa.Column('access_level', sa.String(length=20), nullable=False, comment='접근 수준 (public/internal/restricted/confidential)'),
    sa.Column('default_permission', sa.String(length=20), nullable=False, comment='기본 권한 레벨'),
    sa.Column('inherit_parent_permissions', sa.Boolean(), nullable=False, comment='상위 컨테이너 권한 상속 여부'),
    sa.Column('permission_inheritance_type', sa.String(length=20), nullable=False, comment='권한 상속 방식 (additive/override)'),
    sa.Column('container_owner', sa.String(length=20), nullable=True, comment='컨테이너 소유자 (ADMIN 권한)'),
    sa.Column('permission_managers', sa.ARRAY(sa.String(length=20)), nullable=True, comment='권한 관리자 목록'),
    sa.Column('auto_assign_by_org', sa.Boolean(), nullable=False, comment='조직도 기반 자동 권한 할당'),
    sa.Column('require_approval_for_access', sa.Boolean(), nullable=False, comment='접근 시 승인 필요'),
    sa.Column('approval_workflow_enabled', sa.Boolean(), nullable=False, comment='권한 요청 승인 워크플로우'),
    sa.Column('approvers', sa.ARRAY(sa.String(length=20)), nullable=True, comment='승인자 목록'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='활성화 여부'),
    sa.Column('document_count', sa.Integer(), nullable=False, comment='문서 수'),
    sa.Column('total_knowledge_size', sa.BigInteger(), nullable=False, comment='총 지식 크기 (bytes)'),
    sa.Column('last_knowledge_update', sa.DateTime(timezone=True), nullable=True, comment='마지막 지식 업데이트'),
    sa.Column('user_count', sa.Integer(), nullable=False, comment='접근 권한이 있는 사용자 수'),
    sa.Column('permission_request_count', sa.Integer(), nullable=False, comment='권한 요청 건수'),
    sa.Column('last_permission_update', sa.DateTime(timezone=True), nullable=True, comment='마지막 권한 변경 시간'),
    sa.Column('created_by', sa.String(length=20), nullable=True, comment='생성자'),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성일'),
    sa.Column('last_modified_by', sa.String(length=20), nullable=True, comment='최종 수정자'),
    sa.Column('last_modified_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='최종 수정일'),
    sa.ForeignKeyConstraint(['container_owner'], ['tb_sap_hr_info.emp_no'], ),
    sa.ForeignKeyConstraint(['parent_container_id'], ['tb_knowledge_containers.container_id'], ),
    sa.PrimaryKeyConstraint('container_id')
    )
    op.create_table('tb_user_roles',
    sa.Column('role_id', sa.Integer(), autoincrement=True, nullable=False, comment='역할 ID'),
    sa.Column('user_emp_no', sa.String(length=20), nullable=False, comment='사용자 사번'),
    sa.Column('role_name', sa.String(length=20), nullable=False, comment='역할명 (ADMIN/MANAGER/EDITOR/VIEWER)'),
    sa.Column('role_level', sa.Integer(), nullable=False, comment='역할 레벨 (1=ADMIN, 2=MANAGER, 3=EDITOR, 4=VIEWER)'),
    sa.Column('scope_type', sa.String(length=20), nullable=False, comment='역할 범위 (global/container/department)'),
    sa.Column('scope_value', sa.String(length=50), nullable=True, comment='범위 값 (container_id 또는 dept_code)'),
    sa.Column('role_description', sa.Text(), nullable=True, comment='역할 설명'),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='세부 권한 설정 (JSON)'),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True, comment='역할 유효 시작일'),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True, comment='역할 유효 종료일'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='활성화 여부'),
    sa.Column('assigned_by', sa.String(length=20), nullable=True, comment='역할 할당자'),
    sa.Column('assigned_date', sa.DateTime(timezone=True), nullable=True, comment='역할 할당일'),
    sa.Column('approval_required', sa.Boolean(), nullable=False, comment='승인 필요 여부'),
    sa.Column('approved_by', sa.String(length=20), nullable=True, comment='승인자'),
    sa.Column('approved_date', sa.DateTime(timezone=True), nullable=True, comment='승인일'),
    sa.Column('created_by', sa.String(length=20), nullable=True, comment='생성자'),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성일'),
    sa.Column('last_modified_by', sa.String(length=20), nullable=True, comment='최종 수정자'),
    sa.Column('last_modified_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='최종 수정일'),
    sa.ForeignKeyConstraint(['approved_by'], ['tb_sap_hr_info.emp_no'], ),
    sa.ForeignKeyConstraint(['assigned_by'], ['tb_sap_hr_info.emp_no'], ),
    sa.ForeignKeyConstraint(['user_emp_no'], ['tb_sap_hr_info.emp_no'], ),
    sa.PrimaryKeyConstraint('role_id')
    )
    op.create_table('tb_permission_audit_log',
    sa.Column('audit_id', sa.Integer(), autoincrement=True, nullable=False, comment='감사 로그 ID'),
    sa.Column('user_emp_no', sa.String(length=20), nullable=False, comment='작업 수행자 사번'),
    sa.Column('target_user_emp_no', sa.String(length=20), nullable=True, comment='대상 사용자 사번'),
    sa.Column('container_id', sa.String(length=50), nullable=True, comment='대상 컨테이너 ID'),
    sa.Column('file_id', sa.Integer(), nullable=True, comment='대상 파일 ID'),
    sa.Column('action_type', sa.String(length=30), nullable=False, comment='작업 유형 (grant/revoke/modify/access/approve/reject)'),
    sa.Column('resource_type', sa.String(length=20), nullable=False, comment='리소스 유형 (container/file/role/permission)'),
    sa.Column('old_permission', sa.String(length=20), nullable=True, comment='이전 권한'),
    sa.Column('new_permission', sa.String(length=20), nullable=True, comment='새 권한'),
    sa.Column('action_result', sa.String(length=20), nullable=False, comment='작업 결과 (success/failure/partial)'),
    sa.Column('failure_reason', sa.Text(), nullable=True, comment='실패 사유'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='IP 주소'),
    sa.Column('user_agent', sa.Text(), nullable=True, comment='사용자 에이전트'),
    sa.Column('session_id', sa.String(length=100), nullable=True, comment='세션 ID'),
    sa.Column('request_path', sa.String(length=200), nullable=True, comment='요청 경로'),
    sa.Column('request_method', sa.String(length=10), nullable=True, comment='HTTP 메소드'),
    sa.Column('additional_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='추가 데이터 (JSON)'),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='로그 생성일'),
    sa.ForeignKeyConstraint(['container_id'], ['tb_knowledge_containers.container_id'], ),
    sa.ForeignKeyConstraint(['file_id'], ['tb_file_bss_info.file_bss_info_sno'], ),
    sa.ForeignKeyConstraint(['target_user_emp_no'], ['tb_sap_hr_info.emp_no'], ),
    sa.ForeignKeyConstraint(['user_emp_no'], ['tb_sap_hr_info.emp_no'], ),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_table('tb_permission_management_info',
    sa.Column('management_id', sa.Integer(), autoincrement=True, nullable=False, comment='관리 ID'),
    sa.Column('container_id', sa.String(length=50), nullable=False, comment='컨테이너 ID'),
    sa.Column('user_emp_no', sa.String(length=20), nullable=False, comment='사용자 사번'),
    sa.Column('permission_level', sa.String(length=20), nullable=False, comment='권한 레벨'),
    sa.Column('permission_source', sa.String(length=30), nullable=False, comment='권한 출처'),
    sa.Column('is_inherited', sa.Boolean(), nullable=False, comment='상속 권한 여부'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='활성 상태'),
    sa.Column('valid_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='유효 시작일'),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True, comment='유효 종료일'),
    sa.Column('granted_by', sa.String(length=20), nullable=True, comment='권한 부여자'),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='권한 부여일'),
    sa.Column('revoked_by', sa.String(length=20), nullable=True, comment='권한 취소자'),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True, comment='권한 취소일'),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='추가 메타데이터'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성일'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='수정일'),
    sa.ForeignKeyConstraint(['container_id'], ['tb_knowledge_containers.container_id'], ),
    sa.ForeignKeyConstraint(['granted_by'], ['tb_sap_hr_info.emp_no'], ),
    sa.ForeignKeyConstraint(['revoked_by'], ['tb_sap_hr_info.emp_no'], ),
    sa.ForeignKeyConstraint(['user_emp_no'], ['tb_sap_hr_info.emp_no'], ),
    sa.PrimaryKeyConstraint('management_id')
    )
    op.create_table('tb_permission_requests',
    sa.Column('request_id', sa.Integer(), autoincrement=True, nullable=False, comment='요청 ID'),
    sa.Column('requester_emp_no', sa.String(length=20), nullable=False, comment='요청자 사번'),
    sa.Column('container_id', sa.String(length=50), nullable=False, comment='컨테이너 ID'),
    sa.Column('requested_permission', sa.String(length=20), nullable=False, comment='요청 권한'),
    sa.Column('current_permission', sa.String(length=20), nullable=True, comment='현재 권한'),
    sa.Column('justification', sa.Text(), nullable=False, comment='요청 사유'),
    sa.Column('business_need', sa.Text(), nullable=True, comment='업무 필요성'),
    sa.Column('requested_duration', sa.String(length=50), nullable=True, comment='요청 기간'),
    sa.Column('temp_end_date', sa.DateTime(timezone=True), nullable=True, comment='임시 종료일'),
    sa.Column('request_status', sa.String(length=20), nullable=False, comment='요청 상태'),
    sa.Column('priority_level', sa.String(length=10), nullable=False, comment='우선순위'),
    sa.Column('approver_emp_no', sa.String(length=20), nullable=True, comment='승인자 사번'),
    sa.Column('approval_date', sa.DateTime(timezone=True), nullable=True, comment='승인일'),
    sa.Column('approval_comment', sa.Text(), nullable=True, comment='승인 의견'),
    sa.Column('rejection_reason', sa.Text(), nullable=True, comment='거부 사유'),
    sa.Column('auto_approved', sa.Boolean(), nullable=False, comment='자동 승인 여부'),
    sa.Column('notification_sent', sa.Boolean(), nullable=False, comment='알림 발송 여부'),
    sa.Column('request_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='요청 메타데이터'),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='요청일'),
    sa.Column('last_modified_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='최종 수정일'),
    sa.ForeignKeyConstraint(['approver_emp_no'], ['tb_sap_hr_info.emp_no'], ),
    sa.ForeignKeyConstraint(['container_id'], ['tb_knowledge_containers.container_id'], ),
    sa.ForeignKeyConstraint(['requester_emp_no'], ['tb_sap_hr_info.emp_no'], ),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_table('tb_user_permission_view',
    sa.Column('view_id', sa.Integer(), autoincrement=True, nullable=False, comment='뷰 ID'),
    sa.Column('user_emp_no', sa.String(length=20), nullable=False, comment='사용자 사번'),
    sa.Column('container_id', sa.String(length=50), nullable=False, comment='컨테이너 ID'),
    sa.Column('permission_level', sa.String(length=20), nullable=False, comment='최종 권한 레벨'),
    sa.Column('effective_permission', sa.String(length=20), nullable=False, comment='실제 적용 권한'),
    sa.Column('permission_source', sa.String(length=30), nullable=False, comment='권한 출처'),
    sa.Column('is_inherited', sa.Boolean(), nullable=False, comment='상속 권한 여부'),
    sa.Column('inheritance_path', sa.Text(), nullable=True, comment='상속 경로'),
    sa.Column('container_name', sa.String(length=200), nullable=False, comment='컨테이너 명'),
    sa.Column('container_type', sa.String(length=20), nullable=False, comment='컨테이너 유형'),
    sa.Column('access_level', sa.String(length=20), nullable=False, comment='접근 수준'),
    sa.Column('user_name', sa.String(length=100), nullable=False, comment='사용자 명'),
    sa.Column('department_name', sa.String(length=200), nullable=True, comment='부서명'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='활성 상태'),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True, comment='유효 종료일'),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='최종 업데이트'),
    sa.ForeignKeyConstraint(['container_id'], ['tb_knowledge_containers.container_id'], ),
    sa.ForeignKeyConstraint(['user_emp_no'], ['tb_sap_hr_info.emp_no'], ),
    sa.PrimaryKeyConstraint('view_id')
    )
    op.create_table('tb_user_permissions',
    sa.Column('permission_id', sa.Integer(), autoincrement=True, nullable=False, comment='권한 ID'),
    sa.Column('user_emp_no', sa.String(length=20), nullable=False, comment='사용자 사번'),
    sa.Column('container_id', sa.String(length=50), nullable=False, comment='컨테이너 ID'),
    sa.Column('role_id', sa.String(length=20), nullable=False, comment='역할 ID'),
    sa.Column('permission_type', sa.String(length=20), nullable=False, comment='권한 유형'),
    sa.Column('access_scope', sa.String(length=20), nullable=False, comment='접근 범위'),
    sa.Column('permission_source', sa.String(length=30), nullable=False, comment='권한 출처'),
    sa.Column('source_container_id', sa.String(length=50), nullable=True, comment='권한 출처 컨테이너 ID'),
    sa.Column('sap_role', sa.String(length=50), nullable=True, comment='SAP 역할'),
    sa.Column('restricted_categories', sa.ARRAY(sa.Integer()), nullable=True, comment='제한 카테고리'),
    sa.Column('time_restriction', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='시간 제한'),
    sa.Column('ip_restriction', sa.ARRAY(sa.String(length=50)), nullable=True, comment='IP 제한'),
    sa.Column('granted_by', sa.String(length=20), nullable=True, comment='권한 부여자'),
    sa.Column('granted_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='권한 부여일'),
    sa.Column('expires_date', sa.DateTime(timezone=True), nullable=True, comment='만료일'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='활성화 여부'),
    sa.Column('last_accessed_date', sa.DateTime(timezone=True), nullable=True, comment='마지막 접근일'),
    sa.Column('access_count', sa.Integer(), nullable=False, comment='접근 횟수'),
    sa.ForeignKeyConstraint(['container_id'], ['tb_knowledge_containers.container_id'], ),
    sa.ForeignKeyConstraint(['user_emp_no'], ['tb_sap_hr_info.emp_no'], ),
    sa.PrimaryKeyConstraint('permission_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_user_permissions')
    op.drop_table('tb_user_permission_view')
    op.drop_table('tb_permission_requests')
    op.drop_table('tb_permission_management_info')
    op.drop_table('tb_permission_audit_log')
    op.drop_table('tb_user_roles')
    op.drop_table('tb_knowledge_containers')
    op.drop_index('idx_vs_doc_contents_type', table_name='vs_doc_contents_index')
    op.drop_index('idx_vs_doc_contents_file_sno', table_name='vs_doc_contents_index')
    op.drop_index('idx_vs_doc_contents_embedding', table_name='vs_doc_contents_index', postgresql_using='ivfflat')
    op.drop_index('idx_vs_doc_contents_container', table_name='vs_doc_contents_index')
    op.drop_index('idx_vs_doc_contents_active', table_name='vs_doc_contents_index')
    op.drop_table('vs_doc_contents_index')
    op.drop_index(op.f('ix_vs_doc_contents_chunks_file_bss_info_sno'), table_name='vs_doc_contents_chunks')
    op.drop_index('idx_vs_doc_chunks_page_number', table_name='vs_doc_contents_chunks')
    op.drop_index('idx_vs_doc_chunks_file_sno', table_name='vs_doc_contents_chunks')
    op.drop_index('idx_vs_doc_chunks_embedding', table_name='vs_doc_contents_chunks', postgresql_using='ivfflat')
    op.drop_index('idx_vs_doc_chunks_del_yn', table_name='vs_doc_contents_chunks')
    op.drop_index('idx_vs_doc_chunks_container_id', table_name='vs_doc_contents_chunks')
    op.drop_table('vs_doc_contents_chunks')
    op.drop_table('vs_chat_history_index')
    op.drop_index('idx_tb_user_is_active', table_name='tb_user')
    op.drop_index('idx_tb_user_emp_no', table_name='tb_user')
    op.drop_index('idx_tb_user_email', table_name='tb_user')
    op.drop_table('tb_user')
    op.drop_table('tb_system_settings')
    op.drop_table('tb_search_analytics')
    op.drop_index('idx_tb_sap_hr_info_emp_stats_cd', table_name='tb_sap_hr_info')
    op.drop_index('idx_tb_sap_hr_info_email', table_name='tb_sap_hr_info')
    op.drop_index('idx_tb_sap_hr_info_dept_cd', table_name='tb_sap_hr_info')
    op.drop_index('idx_tb_sap_hr_info_del_yn', table_name='tb_sap_hr_info')
    op.drop_table('tb_sap_hr_info')
    op.drop_table('tb_knowledge_sharing_log')
    op.drop_table('tb_knowledge_categories')
    op.drop_table('tb_knowledge_access_log')
    op.drop_index('idx_tb_file_dtl_info_sj', table_name='tb_file_dtl_info')
    op.drop_index('idx_tb_file_dtl_info_del_yn', table_name='tb_file_dtl_info')
    op.drop_index('idx_tb_file_dtl_info_ctgry_cd', table_name='tb_file_dtl_info')
    op.drop_index('idx_tb_file_dtl_info_authr', table_name='tb_file_dtl_info')
    op.drop_table('tb_file_dtl_info')
    op.drop_index('idx_tb_file_bss_info_del_yn', table_name='tb_file_bss_info')
    op.drop_index('idx_file_bss_info_permission', table_name='tb_file_bss_info')
    op.drop_index('idx_file_bss_info_owner', table_name='tb_file_bss_info')
    op.drop_index('idx_file_bss_info_container', table_name='tb_file_bss_info')
    op.drop_index('idx_file_bss_info_accessed', table_name='tb_file_bss_info')
    op.drop_table('tb_file_bss_info')
    op.drop_table('tb_container_categories')
    op.drop_table('tb_cmns_cd_grp_item')
    op.drop_table('tb_chat_sessions')
    op.drop_table('tb_chat_history')
    op.drop_table('tb_chat_feedback')
    # ### end Alembic commands ###
