"""remove_vector_tables_add_unified_search

Revision ID: 3e19d6566abb
Revises: 300c1a2a7c7f
Create Date: 2025-08-08 17:03:54.126975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3e19d6566abb'
down_revision: Union[str, Sequence[str], None] = '300c1a2a7c7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_document_search_index',
    sa.Column('search_doc_id', sa.Integer(), autoincrement=True, nullable=False, comment='검색 문서 ID'),
    sa.Column('file_bss_info_sno', sa.Integer(), nullable=False, comment='파일 기본 정보 일련번호'),
    sa.Column('knowledge_container_id', sa.String(length=50), nullable=False, comment='지식 컨테이너 ID'),
    sa.Column('document_title', sa.String(length=500), nullable=True, comment='문서 제목'),
    sa.Column('full_content', sa.Text(), nullable=False, comment='문서 전체 내용 또는 주요 섹션'),
    sa.Column('content_summary', sa.Text(), nullable=True, comment='내용 요약 (최대 1000자)'),
    sa.Column('keywords', postgresql.ARRAY(sa.Text()), nullable=True, comment='추출된 키워드 배열'),
    sa.Column('proper_nouns', postgresql.ARRAY(sa.Text()), nullable=True, comment='고유명사 배열'),
    sa.Column('corp_names', postgresql.ARRAY(sa.Text()), nullable=True, comment='회사명/기관명 배열'),
    sa.Column('main_topics', postgresql.ARRAY(sa.Text()), nullable=True, comment='주요 주제/카테고리 배열'),
    sa.Column('document_type', sa.String(length=50), nullable=True, comment='문서 유형 (PDF, DOCX, etc)'),
    sa.Column('page_count', sa.Integer(), nullable=True, comment='페이지 수'),
    sa.Column('content_length', sa.Integer(), nullable=True, comment='전체 내용 길이'),
    sa.Column('language_code', sa.String(length=10), nullable=False, comment='언어 코드'),
    sa.Column('keyword_tsvector', postgresql.TSVECTOR(), nullable=True, comment='키워드 전문검색 벡터'),
    sa.Column('content_tsvector', postgresql.TSVECTOR(), nullable=True, comment='내용 전문검색 벡터'),
    sa.Column('search_weight', sa.Integer(), nullable=False, comment='검색 가중치'),
    sa.Column('access_level', sa.String(length=20), nullable=False, comment='접근 권한 레벨'),
    sa.Column('is_public', sa.Boolean(), nullable=False, comment='공개 문서 여부'),
    sa.Column('indexing_status', sa.String(length=20), nullable=False, comment='색인 상태'),
    sa.Column('last_searched_at', sa.DateTime(timezone=True), nullable=True, comment='마지막 검색 일시'),
    sa.Column('search_count', sa.Integer(), nullable=False, comment='검색 횟수'),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성일'),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='마지막 업데이트'),
    sa.ForeignKeyConstraint(['file_bss_info_sno'], ['tb_file_bss_info.file_bss_info_sno'], ),
    sa.ForeignKeyConstraint(['knowledge_container_id'], ['tb_knowledge_containers.container_id'], ),
    sa.PrimaryKeyConstraint('search_doc_id')
    )
    op.create_index('idx_search_container_type', 'tb_document_search_index', ['knowledge_container_id', 'document_type'], unique=False)
    op.create_index('idx_search_content_tsvector', 'tb_document_search_index', ['content_tsvector'], unique=False, postgresql_using='gin')
    op.create_index('idx_search_file_access', 'tb_document_search_index', ['file_bss_info_sno', 'access_level'], unique=False)
    op.create_index('idx_search_keyword_tsvector', 'tb_document_search_index', ['keyword_tsvector'], unique=False, postgresql_using='gin')
    op.create_index('idx_search_keywords', 'tb_document_search_index', ['keywords'], unique=False, postgresql_using='gin')
    op.create_index('idx_search_proper_nouns', 'tb_document_search_index', ['proper_nouns'], unique=False, postgresql_using='gin')
    op.create_index('idx_search_status', 'tb_document_search_index', ['indexing_status'], unique=False)
    op.create_index('idx_search_topics', 'tb_document_search_index', ['main_topics'], unique=False, postgresql_using='gin')
    op.create_index('idx_search_updated', 'tb_document_search_index', ['last_updated'], unique=False)
    op.drop_table('vs_chat_history_index')
    op.drop_index(op.f('idx_vs_doc_contents_active'), table_name='vs_doc_contents_index')
    op.drop_index(op.f('idx_vs_doc_contents_container'), table_name='vs_doc_contents_index')
    op.drop_index(op.f('idx_vs_doc_contents_embedding'), table_name='vs_doc_contents_index', postgresql_using='ivfflat')
    op.drop_index(op.f('idx_vs_doc_contents_file_sno'), table_name='vs_doc_contents_index')
    op.drop_index(op.f('idx_vs_doc_contents_type'), table_name='vs_doc_contents_index')
    op.drop_table('vs_doc_contents_index')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vs_doc_contents_index',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False, comment='문서 ID'),
    sa.Column('file_bss_info_sno', sa.INTEGER(), autoincrement=False, nullable=False, comment='파일 기본 정보 일련번호'),
    sa.Column('chunk_text', sa.TEXT(), autoincrement=False, nullable=False, comment='문서 내용 (기존 chunk_text)'),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), autoincrement=False, nullable=True, comment='임베딩 벡터 (기존 유지)'),
    sa.Column('chunk_index', sa.INTEGER(), autoincrement=False, nullable=True, comment='청크 인덱스'),
    sa.Column('chunk_size', sa.INTEGER(), autoincrement=False, nullable=True, comment='청크 크기'),
    sa.Column('metadata_json', sa.TEXT(), autoincrement=False, nullable=True, comment='메타데이터 JSON'),
    sa.Column('created_date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True, comment='생성일'),
    sa.Column('knowledge_container_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='지식 컨테이너 ID'),
    sa.Column('document_title', sa.VARCHAR(length=500), autoincrement=False, nullable=True, comment='문서 제목'),
    sa.Column('keywords', sa.TEXT(), autoincrement=False, nullable=True, comment='추출된 키워드 (JSON 배열)'),
    sa.Column('proper_nouns', sa.TEXT(), autoincrement=False, nullable=True, comment='고유명사 (JSON 배열)'),
    sa.Column('document_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='문서 유형 (PDF, DOCX, etc)'),
    sa.Column('content_length', sa.INTEGER(), autoincrement=False, nullable=True, comment='전체 내용 길이'),
    sa.Column('content_summary', sa.TEXT(), autoincrement=False, nullable=True, comment='내용 요약'),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='활성화 여부'),
    sa.Column('last_updated', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True, comment='마지막 업데이트'),
    sa.PrimaryKeyConstraint('id', name=op.f('vs_doc_contents_index_pkey'))
    )
    op.create_index(op.f('idx_vs_doc_contents_type'), 'vs_doc_contents_index', ['document_type'], unique=False)
    op.create_index(op.f('idx_vs_doc_contents_file_sno'), 'vs_doc_contents_index', ['file_bss_info_sno'], unique=False)
    op.create_index(op.f('idx_vs_doc_contents_embedding'), 'vs_doc_contents_index', ['embedding'], unique=False, postgresql_using='ivfflat')
    op.create_index(op.f('idx_vs_doc_contents_container'), 'vs_doc_contents_index', ['knowledge_container_id'], unique=False)
    op.create_index(op.f('idx_vs_doc_contents_active'), 'vs_doc_contents_index', ['is_active'], unique=False)
    op.create_table('vs_chat_history_index',
    sa.Column('index_id', sa.INTEGER(), autoincrement=True, nullable=False, comment='인덱스 ID'),
    sa.Column('chat_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='채팅 ID'),
    sa.Column('message_vector', pgvector.sqlalchemy.vector.VECTOR(dim=1024), autoincrement=False, nullable=False, comment='메시지 벡터 (1024차원)'),
    sa.Column('response_vector', pgvector.sqlalchemy.vector.VECTOR(dim=1024), autoincrement=False, nullable=True, comment='응답 벡터 (1024차원)'),
    sa.Column('conversation_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='대화 메타데이터 (JSON)'),
    sa.Column('knowledge_container_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='지식 컨테이너 ID'),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='활성화 여부'),
    sa.Column('created_date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True, comment='생성일'),
    sa.Column('last_updated', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True, comment='마지막 업데이트'),
    sa.PrimaryKeyConstraint('index_id', name=op.f('vs_chat_history_index_pkey'))
    )
    op.drop_index('idx_search_updated', table_name='tb_document_search_index')
    op.drop_index('idx_search_topics', table_name='tb_document_search_index', postgresql_using='gin')
    op.drop_index('idx_search_status', table_name='tb_document_search_index')
    op.drop_index('idx_search_proper_nouns', table_name='tb_document_search_index', postgresql_using='gin')
    op.drop_index('idx_search_keywords', table_name='tb_document_search_index', postgresql_using='gin')
    op.drop_index('idx_search_keyword_tsvector', table_name='tb_document_search_index', postgresql_using='gin')
    op.drop_index('idx_search_file_access', table_name='tb_document_search_index')
    op.drop_index('idx_search_content_tsvector', table_name='tb_document_search_index', postgresql_using='gin')
    op.drop_index('idx_search_container_type', table_name='tb_document_search_index')
    op.drop_table('tb_document_search_index')
    # ### end Alembic commands ###
